spring:
  application:
    name: vacation-calculate
server:
  port: 7777
calc:
  avgMonthDays: 29.3
  holidays:
    - "01.01"
    - "02.01"
    - "03.01"
    - "04.01"
    - "05.01"
    - "06.01"
    - "07.01"
    - "08.01"
    - "23.02"
    - "08.03"
    - "01.05"
    - "02.05"
    - "08.05"
    - "09.05"
    - "12.06"
    - "13.06"
    - "04.11"
    - "31.12"
  precision: 2